volumes:
  authdbvol:

services:
  authdb:
    image: mysql:8
    volumes:
      - authdbvol:/var/lib/mysql
    ports:
      - 23306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=something
      - MYSQL_DATABASE=UserAuthDB
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbsomething

  adminer:
    image: adminer:latest
    ports:
      - 18080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=authdb

  usersservice:
    image: stoplight/prism:4
    # volumes:
    #   - ./user_spec.yml:/user_spec.yml
    ports:
      - 14010:4010
    command: ["mock", "-h", "0.0.0.0", "https://raw.githubusercontent.com/friendpost-july/user-spec/main/user_spec.yml"]
    # command: ["mock", "-h", "0.0.0.0", "/user_spec.yml"]